name: unit-tests

concurrency:
  group: unit-tests
  cancel-in-progress: true

on:
  push:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake qt6-base-dev qt6-tools-dev-tools libgl1-mesa-dev

      - name: Run tests
        working-directory: ./project/code/
        run: |
          cmake --preset test-only
          cmake --build build
          ctest --test-dir build --output-on-failure
